name: Run and Cache Benchmarks

on:
  pull_request:

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run benchmarks on target - solvers
        run: cargo bench -- solvers --exact | tail -n +6  > results_target.txt

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_results_target
          path: ./results_target.txt
          if-no-files-found: error

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Run benchmarks on PR - solvers
        run: cargo bench -- solvers --exact | tail -n +6 > results_pr.txt

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_results_pr
          path: ./results_pr.txt
          if-no-files-found: error

      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: ${{ github.event_path }}
